DROP TABLE IF EXISTS KayttajaDrinkki CASCADE;
DROP TABLE IF EXISTS DrinkkiRaakaAine CASCADE;
DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Drinkki CASCADE;
DROP TABLE IF EXISTS RaakaAine CASCADE;